### ISSUE TITLE
share the dataset

### ISSUE THREAD

**Issue by Emily-zcy** [Hanchen-Wang/GoGNN#1]
Hello, have you finished your experiment code? Can you share the data set?

**Comment by weixx2** [comment]
Do you have get the dataset and successfully ran the code? could please share me the dataset? especially the negative samples

**Comment by Hanchen-Wang** [comment]
Hi for the dataset, since they are too large to share, please send me an email (hanchenw.au@gmail.com), I will share the link of the datasets.
